/**
 * The set of possible event-keys
 */
export enum EventKey {
    MESSAGE_SEND = "MESSAGE_SEND",
    // ORDER
    ORDER_FINALIZED = "ORDER_FINALIZED",
    ORDER_CREATE = "ORDER_CREATE",
    ORDER_CANCEL = "ORDER_CANCEL",
    ORDER_ACCEPT = "ORDER_ACCEPT",
    ORDER_REJECT = "ORDER_REJECT",
    ORDER_PAID = "ORDER_PAID",
    ORDER_REFUNDED = "ORDER_REFUNDED",
    DELIVERY_CONFIRMED_SELLER = "DELIVERY_CONFIRMED_SELLER",
    DELIVERY_CONFIRMED_BUYER = "DELIVERY_CONFIRMED_BUYER",
    PAYMENT_CONFIRMED_SELLER = "PAYMENT_CONFIRMED_SELLER",
    PAYMENT_CONFIRMED_BUYER = "PAYMENT_CONFIRMED_BUYER",
    DELIVERY_TIME_CHANGED = "DELIVERY_TIME_CHANGED",
    // TRANSACTION:
    PAYMENT_SENT = "PAYMENT_SENT",
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    PAYIN_FAILED = "PAYIN_FAILED",
    PAYOUT_FAILED = "PAYOUT_FAILED",
    PAYIN_SUCCESS = "PAYIN_SUCCESS",
    PAYOUT_SUCCESS = "PAYOUT_SUCCESS",
    // ITEM-REVIEW
    ITEM_REVIEW_CREATED = "ITEM_REVIEW_CREATED",
    CAMPAIGN_REVIEW_CREATED = "CAMPAIGN_REVIEW_CREATED",
    PROFILE_REVIEW_CREATED = "PROFILE_REVIEW_CREATED",
    // BID:
    BID_RECEIVED = "BID_RECEIVED",
    BID_ACCEPTED = "BID_ACCEPTED",
    BID_REJECTED = "BID_REJECTED",
    // KYC:
    KYC_SUCCESS = "KYC_SUCCESS",
    KYC_FAILED = "KYC_FAILED"
}